config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { registrations: 'registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :posts do 
	resources :comments
end 

root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	has_many :comments, dependent: :destroy

	validates :image, presence: true

	has_attached_file :image, styles: {:medium => "640x"}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  validates :user_name, presence: true, length: { minimum: 4, maximum: 12 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_post
	def new 
	
	end 

	def create 
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			flash[:success] = "Your comment was created successfully!"
			redirect_to root_path
		else 
			flash[:alert] = "Check the comment form, because something went horribly wrong."
			render root_path
		end 
	end 

	def edit 
	end 

	def update 
	end 

	def destroy 
		@comment = @post.comments.find(params[:id])

		@comment.destroy 
		flash[:success] = "Comment destroyed."
		redirect_to root_path
	end 
end 

private 
	def set_post
		@post = Post.find(params[:post_id])
	end 

	def comment_params
 	 	params.require(:comment).permit(:content)
	end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :owned_post, only: [:edit, :update, :destroy]

def index 
	@posts = Post.all
end 

def new 
	@post = current_user.posts.build
end 

def create 
	@post = current_user.posts.build(post_params)
	if @post.save 
		flash[:success] = "Your post has been created!"
		redirect_to @post
	else 
		flash[:alert] = "Halt, you fiend! You need an image to post here!"
		render :new
	end
end

def show 
	@post = Post.find(params[:id])
end 

def edit 
	@post = Post.find(params[:id])

end 

def update 
	@post = Post.find(params[:id])
  	@post.update(post_params)
  	if @post.save 
  		flash[:success] = "Post updated hombre!"
  		redirect_to(post_path(@post))
  	else 
  		flash[:alert] = "Update unsuccessful."
  		render :edit
  	end
  end 

def destroy 
	@post = Post.find(params[:id])
	
	if @post.destroy
		flash[:success] = "Problem solved! Post deleted."
		redirect_to posts_path
	else 
		flash[:alert] = "Post failed to be deleted."
		render :edit
	end 
end 

end 

private 

def post_params
	params.require(:post).permit(:caption, :image)
end 

def owned_post 
	@post = Post.find(params[:id])

	unless @post.user.id == current_user.id
		flash[:alert] = "That post doesn't belong to you!"
		redirect_to root_path
end 

end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)
		{
			:success => 'alert-success', 
			:error => 'alert-danger', 
			:alert => 'alert-warning', 
			:notice => 'alert-info'
		}[flash_type.to_sym] || flash_type.to_s
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>

  <body>
    <nav class="navbar navbar-default">
      <div class="navbar-container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">
            <%= link_to "Photogram", root_path %>
          </div>
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

            <%if user_signed_in? %> 

              <li> 
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </li>

              <li>
              <%= link_to "New Post", new_post_path %>
            </li>

            <% else %> 

              <li>
                <%= link_to "Register", new_user_registration_path %>
              </li>
              <li> 
                <%= link_to "Log In", new_user_session_path %> 
              </li>

             <% end %> 

          </ul>
        </div>
      </div>
    </nav>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>PhotogramTDD</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

      <body>
        <%= render 'layouts/navigation' %> 
        <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
        <% end %>

      <!--- <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p> ---> 

        <%= yield %>
      </body>
  </html>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<h1 align= "center"> News Feed</h1>

<div class="posts-wrapper">
  <% @posts.each do |post| %> 
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <br /> 
      <div class="caption">
        <div class="user-name">
          <%= post.user.user_name %>
        </div>
        <%= post.caption %>
      </div>
      <% if post.comments %>
        <% post.comments.each do |comment| %>
          <div class="comment">
            <div class="user-name">
              <%= comment.user.user_name %>
            </div>
            <div class="comment-content">
              <%= comment.content %>
            </div>
            <% if comment.user == current_user %>
              <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
                <span class="glyphicon glyphicon-remove delete-comment"></span>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <div>
        <br />
        <%= form_for [post, post.comments.new] do |f| %>    
          <%= f.label :name, 'Comment' %> 
          <%= f.text_field :content, placeholder: 'Add a comment...' %>
          <span> <%= f.submit "Submit" %>  </span>
        <% end %>
      </div>
    </div>  
    <% end %> 
  </div>
</div>

app/views/posts/new.html.erb
<div class = "col-md-6 col-md-offset-3">  
  <h1 align = "center"> Upload New Post </h1>
  <div class="form-wrapper">
    <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
      <div class="form-group">
        <%= f.input :image %>
      </div>
      <div class="form-group text-center">
        <%= f.input :caption %>
      </div>
      <div class="form-group text-center">
        <%= f.button :submit, class: 'btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
       <%= @post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
    
    <% if @post.user.id == current_user.id %> 
      
      <div class="text-center edit-links">
        
          <%= link_to "Cancel", posts_path %>
          |
          <%= link_to "Edit Post", edit_post_path(@post) %>

      </div>

    <% else %> 
      
      <div class="text-center edit-links">
        <%= link_to "Cancel", posts_path %>
      </div>
    <% end %> 

  </div>

</div>